### ISSUE TITLE
User Friendly Device

### ISSUE THREAD

**Issue by Gonza10V** [Open-Hardware-Leaders/Corchea#43]
## 1. Hypothesis: We believe that
We believe an easy to use kit for corchea will lower the barrier to end users

## 2. Experiment: To verify it we will do
Make a workshop where people use Corchea (beta) kit and give feedback about their usage.

### Materials needed
- Corchea Kits
- Volunteers
- Survey
- Reward

### Tasks
- [ ] Organize a workshop
- [ ] Define the content of a Corchea Beta Kit
-  [ ] Make some Corchea Beta Kits
- [ ] Define the protocol 
- [ ] Make a good survey, relevant user friendly questions
- [ ] Call for volunteers
- [ ] Get some rewards for the volunteers
- [ ] Do a Corchea workshop
- [ ] Take the survey
- [ ] Analyze the survey
- [ ] Use the feedback for the backlog

## 3. Metric: and we will measure the following indicators
- End users interest in Corchea and the project during the workshop
- Participants agree and engage in fill in a form, or go to my repository and give me feedback
- Lead users(at least one expert in this domain) criticise and engage in improving Corchea

## 4. Criteria: We have partially validated the idea if
- We get more then 10 volunteers for the workshop
- More than half of the volunteers follow and finish the protocol without help
- From 1 to 5 we should be in average at 3 or above in user friendly

**Comment by jurra** [comment]
Hi @Gonza10V, Great that you are using the test card format.
My first remark with this one is that this hypothesis: 
(_Make an user friendly device will remove entry barriers to use Corchea_) Is not formulated in a way that is easy to test (A testable hypothesis). 

I am going to rephrase it in different ways.

_We believe that a proper User Experience with Corchea involves turning it into an easy to use kit.
We believe an easy to use kit for corchea will lower the barrier to end users
We believe that well prepared events and workshops will also lower the barrier to end users._

Experiment:
- Make a workshop where people use Corchea (beta) kit and give feedback about their usage.

3. Metric: and we will measure the following indicators
- End users interest in Corchea and the project during the workshop
- Participants agree and engage in fill in a form, or go to my repository and give me feedback
- Lead users(at least onevvexpert in this domain) critizce and engage in improving Corchea

4. Criteria: We have partially validated the idea if
- It is easy to get a first simple result with corchea (Maybe specify it more, what concrete result people can get from a first usage of Corchea??)
- The kit is simple to use, is robust, and delivers the functionality
- If the user journey is well implement in the product
....Make it as specific as you can with regard to corchea....
